# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
  - neko-jpg

patreon: # Replace with a single Patreon username
  # - resnetbk

open_collective: # Replace with a single Open Collective username
  # - resnetbk

ko_fi: # Replace with a single Ko-fi username
  # - resnetbk

tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
  # - pypi/resnet-bk

community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry

liberapay: # Replace with a single Liberapay username
  # - resnetbk

issuehunt: # Replace with a single IssueHunt username
  # - resnetbk

otechie: # Replace with a single Otechie username
  # - resnetbk

lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry

custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
  # - https://resnet-bk.org/donate
