
class ReadmeGenerator:
    @staticmethod
    def generate(model_name, config, skills=None):
        """
        Generates a Model Card (README.md) for Hugging Face.
        """
        md = f"""---
language:
- en
- ja
tags:
- muse
- pytorch
- text-generation
license: apache-2.0
---

# 🧬 {model_name}

This model is a custom evolution of the **MUSE (ResNet-BK)** architecture.
It has been trained using the **MUSE Evolution Protocol**.

## 📊 Model Details
- **Architecture:** ResNet-BK (Birman-Schwinger Kernel)
- **Parameters:** {config.get('d_model', 'N/A')} dim / {config.get('n_layers', 'N/A')} layers
- **Context Length:** {config.get('n_seq', 'N/A')} tokens

## 🧠 Capabilities (Future IQ)
"""
        if skills:
            md += "| Skill | Score |\n|---|---|\n"
            for k, v in skills.items():
                md += f"| {k} | {v:.1f} |\n"
        else:
            md += "Skills evaluation not available.\n"

        md += """
## 🚀 Usage

```python
from src.models.phase4.integrated_model import Phase4IntegratedModel
# Load your model here
```

## ⚖️ Ethics & Safety
This model includes the **Phase 4 Ethical Safeguards** (Topological Security Knots) to prevent harmful outputs.

---
*Generated by MUSE Deploy Studio*
"""
        return md

    @staticmethod
    def infer_tags(config):
        tags = ["muse", "pytorch", "causal-lm"]

        # Heuristic tagging
        mix = config.get('dataset_mix', {})
        if any('code' in k for k in mix):
            tags.append("code-generation")
        if any('japanese' in k for k in mix):
            tags.append("multilingual")
            tags.append("ja")
        if any('math' in k for k in mix):
            tags.append("math")

        return tags
